name: Deploy to Github Pages

on: workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - name: Install dependencies
      run: npm install
    - name: Build proyect
      run: npm run build
    
  # build:
  #   needs: [setup]
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Build proyect
  #     run: npm run build
      
  # deploy:
  #   needs: [setup, build]
   

            
