name: Deploy to Github Pages

on:
  push:
    branches:
      - "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - uses: nanasess/setup-chromedriver@v2
        with:
          # Optional: do not specify to match Chrome's version
          chromedriver-version: '88.0.4324.96'
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - run: npm install eslint --global
      - run: npm install --save-dev @typescript-eslint/parser @typescript-eslint/eslint-plugin eslint typescript
      - run: eslint . --ext .js,.jsx,.ts,.tsx
      - run: npm test
      - run: npm ci
      - run: npm run build --prod
      - run: cp ./dist/todo-app/browser/index.html ./dist/todo-app/browser/404.html

      - uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/todo-app/browser


            
