name: Deployment Pipeline

# on:
#   push:
#     branches:
#       - "main"

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: npm run build:prod
    - name: Prepare and Deploy
      run: npx angular-cli-ghpages --dir=dist/todo-app/browser --no-silent
    # - name: Build
    #   run: npm run build:prod
    # - name: Upload Artifact
    #   uses: actions/upload-pages-artifact@v3
    #   with:
    #     name: github-pages
    #     path: dist/todo-app
    # - name: Deploy GitHub Pages site
    #   uses: actions/deploy-pages@v4.0.2

            
