name: Deploy to Github Pages

on: workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: '20'
    - run: npm install
    
  build:
    needs: [setup]
    runs-on: ubuntu-latest

    steps:
    - run: npm run build
  # deploy:
  #   needs: [setup, build]
   

            
